# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: mastergc
  CLOUD_SQL_PASSWORD: mastergc4312
  CLOUD_SQL_DATABASE_NAME: demo
  CLOUD_SQL_CONNECTION_NAME: ml-project-4312:us-central1:gc-ml-project
# [END gae_python37_cloudsql_config]