apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-10T14:29:53Z"
  generation: 6
  labels:
    app: cloud-project
  name: cloud-project
  namespace: default
  resourceVersion: "37586"
  selfLink: /apis/apps/v1/namespaces/default/deployments/cloud-project
  uid: 72b2b319-8adf-4b45-9528-819590cec4bd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cloud-project
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cloud-project
    spec:
      containers:
      - image: asia.gcr.io/amiable-mode-289808/cloud_project@sha256:8a00dc6de04ffc3fae832847a8e24024a4eef2495ebb936e1ea34052b05f12c2
        imagePullPolicy: IfNotPresent
        name: cloud-project-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-10T14:29:53Z"
    lastUpdateTime: "2020-11-10T14:30:27Z"
    message: ReplicaSet "cloud-project-58b8ff586d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-11-10T16:42:53Z"
    lastUpdateTime: "2020-11-10T16:42:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
